# Generated by Django 5.0.8 on 2024-08-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
